### ISSUE TITLE
Update AngularJS to implement extra round trip to get the user claims

### ISSUE THREAD

**Issue by damienbod** [damienbod/AspNet5IdentityServerAngularImplicitFlow#38]
This requires an extra round trip with IdentityServer rc4 to get the user claims, roles, no longer included in the id_token

**Comment by RolfVeinoeSorensen** [comment]
Hi Damien

First of all thank you for a great reference project. I am using the ResourceWithIdentityServerWithClient project as inspiration for my site.

This bug is it related to when I log in and get returned to the ng2 spa then the link still says log in until I log in again then admin links starts to work and link changes to log out?

It would be great if you could help me suggest a solution.

**Comment by damienbod** [comment]
Hi @RolfVeinoeSorensen, you need to save the user data, security tokens local some where on the client, local storage, cookies, redux or whatever and then implement a service or a guard which can be used to switch between a logged in compoenents, and the log in component
