### ISSUE TITLE
Update webpack production build to fulfil the max 250kb warning

### ISSUE THREAD

**Issue by damienbod** [damienbod/AspNet5IdentityServerAngularImplicitFlow#41]
code splitting
lazy loading

**Comment by pomeara** [comment]
Hi Damien, firstly wanted to say you have a great set of template projects and samples to help folks like myself jump into this A2 world!

I have been trying to get this up and running and have bumped into a few different issues.

1) The size of both prod and dev builds for the app.bundle.js is > 10MB (I assume lazy loading may assist with this - however I was surprised that tree shaking did not shake out a little more size) - I assume that this thread / issue deals with this item?

2) I've included a separate UI (am using Core.UI) and changed the app to use the # location strategy, and I believe I am using lazy loading now via the routing mechanism I'm using however I find that these items are not found when the app loads (I receive the error : Error: Cannot find module './app/ui/home/home.module)

3) Am curious about the addition of extra properties on the ApplicationUser class for IsAdmin, etc.... as I'm looking at moving them into a user claim and actually am looking to attempt to use the AspNetIdentity tables to store this information rather than have it hard coded in multiple places.

So was curious if you could assist with some of your wisdom for a newbie such as myself.  I have my modified version in my repo 'SpaTemplate' which also includes a separate project which uses .tt templates to auto generate several items (Api Controllers, TS domain and services).

Thanks in advance
Pat

P.S. Please forgive me if this is not the right spot to post these items
