### ISSUE TITLE
Implement silent renew

### ISSUE THREAD

**Issue by damienbod** [damienbod/AspNet5IdentityServerAngularImplicitFlow#47]

**Comment by urbanhusky** [comment]
Hi, how could silent renewal be implemented?

**Comment by damienbod** [comment]
Hi @urbanhusky 
I want to implement as defined here:
http://openid.net/specs/openid-connect-session-1_0-ID4.html

hidden iframes can be used in angular.

Greetings Damien

**Comment by damienbod** [comment]
Hi @urbanhusky 
http://openid.net/specs/openid-connect-session-1_0-ID4.html

This spec will not work for this use case. To refresh the tokens, you need to check the token expired time and login if the tokens will exired within a certain time. If you do this in the main page, the page is refreshed which is useful not welcome. To do this, for example without losing form data, you would have to use a popup for the login. 

OpenID Connect Implicit Flow does not supply a way of refrehing the tokens

Greetings Damien

**Comment by damienbod** [comment]
The check session can be used to check if the server session has changed (not log out)  This is useful in a SSO for multiple applications.

**Comment by urbanhusky** [comment]
I've gotten silent renewal to work by using `oidc-client-js`. The callback is just plain html+js (because the app is rather large and there is no need to spin up the app in an iframe if something easier works just as well)

I have to iron out some other issues in my own code and maybe I can provide some example code on how to include oidc-client in an Angular application with proper observables etc. some day.

**Comment by damienbod** [comment]
@urbanhusky 2 questions
When a user logs out from the server, does your client application notice this?
Is the login in a popup?

Greetings Damien

**Comment by damienbod** [comment]
I'm now implementing this using iframes and the token expire time.

**Comment by damienbod** [comment]
now implemented

**Comment by urbanhusky** [comment]
@damienbod the session check in `oicd-client` notices when the session ended in the current browser. I'm using that event (and the token expired event) to trigger a signout for better UX. 
IdentityServer 4 acts as our OP (with ASP.NET Core Identity).

I did not want a SSO/SLO so this works great for our application. I however have since switched to the .net code from the AspNet Identity Quickstart because that works better for me (should respect the redirect url, better separation of concerns).

I would really recommend switching to the `oidc-client` since this offers all you need out of the box. I was able to adapt it into my code (based on this repository) rather quickly.
