### ISSUE TITLE
isAuthorized and hasAdminRole can be changed via storage

### ISSUE THREAD

**Issue by nukec** [damienbod/AspNet5IdentityServerAngularImplicitFlow#63]
I mean this is not secured obviously, I can just change the false to true and get access to some pages. How can we secure this better?

**Comment by damienbod** [comment]
Hi @nukec 
true, but this is a SPA. If you set this to true, the APIs will still not work, because the admin rights are missing.

2 things need to be validated:
No Admin data should be returned to a non-Admin
Admin requests can be only executed by admins

Otherwise you need server side rendering.

Greetings Damien

**Comment by nukec** [comment]
@damienbod I think one way would be to do a request to connect/userinfo to auth server each time page is opened and retrieve role each time, instead of only when login happens. so in case anyone changes role it updates itself each time after request. Do you think this would be overkill for auth server?

Or is there simply custom not allowed or just redirection to home screen better solution if I am trying to do request to [Authorize(Role="admin")] for example when hasAdminRole is true by hijacking?

**Comment by damienbod** [comment]
but think about round trips and performance
